# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "/home/dipen/Kintex7/BasictTest/BasictTest.runs/synth_1/design_1_wrapper.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
OPTRACE "synth_1" START { ROLLUP_AUTO }
set_param chipscope.maxJobs 6
set_param xicom.use_bs_reader 1
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xc7k480tffg1156-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/dipen/Kintex7/BasictTest/BasictTest.cache/wt [current_project]
set_property parent.project_path /home/dipen/Kintex7/BasictTest/BasictTest.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part_repo_paths {/tools/Xilinx/Vivado/2020.1/data/boards/board_files} [current_project]
set_property board_part tiferking.cn:ypcb003381p1:part0:1.0 [current_project]
set_property ip_output_repo /home/dipen/Kintex7/BasictTest/BasictTest.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
read_vhdl -library xil_defaultlib /home/dipen/Kintex7/BasictTest/BasictTest.srcs/sources_1/bd/design_1/hdl/design_1_wrapper.vhd
add_files /home/dipen/Kintex7/BasictTest/BasictTest.srcs/sources_1/bd/design_1/design_1.bd
set_property used_in_implementation false [get_files -all /home/dipen/Kintex7/BasictTest/BasictTest.srcs/sources_1/bd/design_1/ip/design_1_xdma_0_2/ip_4/pcie2_fifo_generator_tgt_brdg.xdc]
set_property used_in_implementation false [get_files -all /home/dipen/Kintex7/BasictTest/BasictTest.srcs/sources_1/bd/design_1/ip/design_1_xdma_0_2/ip_3/pcie2_fifo_generator_dma_cpl.xdc]
set_property used_in_implementation false [get_files -all /home/dipen/Kintex7/BasictTest/BasictTest.srcs/sources_1/bd/design_1/ip/design_1_xdma_0_2/ip_2/xdma_v4_1_6_blk_mem_64_noreg_be_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/dipen/Kintex7/BasictTest/BasictTest.srcs/sources_1/bd/design_1/ip/design_1_xdma_0_2/ip_1/xdma_v4_1_6_blk_mem_64_reg_be_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/dipen/Kintex7/BasictTest/BasictTest.srcs/sources_1/bd/design_1/ip/design_1_xdma_0_2/ip_0/source/design_1_xdma_0_2_pcie2_ip-PCIE_X0Y0.xdc]
set_property used_in_implementation false [get_files -all /home/dipen/Kintex7/BasictTest/BasictTest.srcs/sources_1/bd/design_1/ip/design_1_xdma_0_2/ip_0/synth/design_1_xdma_0_2_pcie2_ip_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/dipen/Kintex7/BasictTest/BasictTest.srcs/sources_1/bd/design_1/ip/design_1_xdma_0_2/design_1_xdma_0_2_board.xdc]
set_property used_in_implementation false [get_files -all /home/dipen/Kintex7/BasictTest/BasictTest.srcs/sources_1/bd/design_1/ip/design_1_xdma_0_2/source/design_1_xdma_0_2_pcie3_7vx_ip.xdc]
set_property used_in_implementation false [get_files -all /home/dipen/Kintex7/BasictTest/BasictTest.srcs/sources_1/bd/design_1/ip/design_1_xdma_0_2/synth/design_1_xdma_0_2_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/dipen/Kintex7/BasictTest/BasictTest.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_0_1/design_1_axi_gpio_0_1_board.xdc]
set_property used_in_implementation false [get_files -all /home/dipen/Kintex7/BasictTest/BasictTest.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_0_1/design_1_axi_gpio_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/dipen/Kintex7/BasictTest/BasictTest.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_0_1/design_1_axi_gpio_0_1.xdc]
set_property used_in_implementation false [get_files -all /home/dipen/Kintex7/BasictTest/BasictTest.srcs/sources_1/bd/design_1/ip/design_1_axi_iic_0_0/design_1_axi_iic_0_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/dipen/Kintex7/BasictTest/BasictTest.srcs/sources_1/bd/design_1/ip/design_1_axi_iic_0_0/design_1_axi_iic_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/dipen/Kintex7/BasictTest/BasictTest.srcs/sources_1/bd/design_1/ip/design_1_util_ds_buf_1/design_1_util_ds_buf_1_board.xdc]
set_property used_in_implementation false [get_files -all /home/dipen/Kintex7/BasictTest/BasictTest.srcs/sources_1/bd/design_1/ip/design_1_util_ds_buf_1/design_1_util_ds_buf_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/dipen/Kintex7/BasictTest/BasictTest.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_1/bd_48ac_psr0_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/dipen/Kintex7/BasictTest/BasictTest.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_1/bd_48ac_psr0_0.xdc]
set_property used_in_implementation false [get_files -all /home/dipen/Kintex7/BasictTest/BasictTest.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_2/bd_48ac_psr_aclk_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/dipen/Kintex7/BasictTest/BasictTest.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_2/bd_48ac_psr_aclk_0.xdc]
set_property used_in_implementation false [get_files -all /home/dipen/Kintex7/BasictTest/BasictTest.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_3/bd_48ac_psr_aclk1_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/dipen/Kintex7/BasictTest/BasictTest.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_3/bd_48ac_psr_aclk1_0.xdc]
set_property used_in_implementation false [get_files -all /home/dipen/Kintex7/BasictTest/BasictTest.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_4/bd_48ac_psr_aclk2_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/dipen/Kintex7/BasictTest/BasictTest.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_4/bd_48ac_psr_aclk2_0.xdc]
set_property used_in_implementation false [get_files -all /home/dipen/Kintex7/BasictTest/BasictTest.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_5/bd_48ac_arsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/dipen/Kintex7/BasictTest/BasictTest.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_6/bd_48ac_rsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/dipen/Kintex7/BasictTest/BasictTest.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_7/bd_48ac_awsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/dipen/Kintex7/BasictTest/BasictTest.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_8/bd_48ac_wsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/dipen/Kintex7/BasictTest/BasictTest.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_9/bd_48ac_bsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/dipen/Kintex7/BasictTest/BasictTest.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_13/bd_48ac_s00a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/dipen/Kintex7/BasictTest/BasictTest.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_14/bd_48ac_sarn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/dipen/Kintex7/BasictTest/BasictTest.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_15/bd_48ac_srn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/dipen/Kintex7/BasictTest/BasictTest.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_16/bd_48ac_sawn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/dipen/Kintex7/BasictTest/BasictTest.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_17/bd_48ac_swn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/dipen/Kintex7/BasictTest/BasictTest.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_18/bd_48ac_sbn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/dipen/Kintex7/BasictTest/BasictTest.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_22/bd_48ac_s01a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/dipen/Kintex7/BasictTest/BasictTest.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_23/bd_48ac_sarn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/dipen/Kintex7/BasictTest/BasictTest.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_24/bd_48ac_srn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/dipen/Kintex7/BasictTest/BasictTest.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_25/bd_48ac_sawn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/dipen/Kintex7/BasictTest/BasictTest.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_26/bd_48ac_swn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/dipen/Kintex7/BasictTest/BasictTest.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_27/bd_48ac_sbn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/dipen/Kintex7/BasictTest/BasictTest.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_28/bd_48ac_m00s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/dipen/Kintex7/BasictTest/BasictTest.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_29/bd_48ac_m00arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/dipen/Kintex7/BasictTest/BasictTest.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_30/bd_48ac_m00rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/dipen/Kintex7/BasictTest/BasictTest.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_31/bd_48ac_m00awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/dipen/Kintex7/BasictTest/BasictTest.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_32/bd_48ac_m00wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/dipen/Kintex7/BasictTest/BasictTest.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_33/bd_48ac_m00bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/dipen/Kintex7/BasictTest/BasictTest.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_35/bd_48ac_m01s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/dipen/Kintex7/BasictTest/BasictTest.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_36/bd_48ac_m01arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/dipen/Kintex7/BasictTest/BasictTest.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_37/bd_48ac_m01rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/dipen/Kintex7/BasictTest/BasictTest.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_38/bd_48ac_m01awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/dipen/Kintex7/BasictTest/BasictTest.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_39/bd_48ac_m01wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/dipen/Kintex7/BasictTest/BasictTest.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_40/bd_48ac_m01bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/dipen/Kintex7/BasictTest/BasictTest.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_42/bd_48ac_m02s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/dipen/Kintex7/BasictTest/BasictTest.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_43/bd_48ac_m02arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/dipen/Kintex7/BasictTest/BasictTest.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_44/bd_48ac_m02rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/dipen/Kintex7/BasictTest/BasictTest.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_45/bd_48ac_m02awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/dipen/Kintex7/BasictTest/BasictTest.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_46/bd_48ac_m02wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/dipen/Kintex7/BasictTest/BasictTest.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_47/bd_48ac_m02bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/dipen/Kintex7/BasictTest/BasictTest.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_49/bd_48ac_m03s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/dipen/Kintex7/BasictTest/BasictTest.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_50/bd_48ac_m03arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/dipen/Kintex7/BasictTest/BasictTest.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_51/bd_48ac_m03rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/dipen/Kintex7/BasictTest/BasictTest.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_52/bd_48ac_m03awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/dipen/Kintex7/BasictTest/BasictTest.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_53/bd_48ac_m03wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/dipen/Kintex7/BasictTest/BasictTest.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_54/bd_48ac_m03bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/dipen/Kintex7/BasictTest/BasictTest.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_56/bd_48ac_m04s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/dipen/Kintex7/BasictTest/BasictTest.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_57/bd_48ac_m04arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/dipen/Kintex7/BasictTest/BasictTest.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_58/bd_48ac_m04rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/dipen/Kintex7/BasictTest/BasictTest.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_59/bd_48ac_m04awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/dipen/Kintex7/BasictTest/BasictTest.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_60/bd_48ac_m04wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/dipen/Kintex7/BasictTest/BasictTest.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_61/bd_48ac_m04bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/dipen/Kintex7/BasictTest/BasictTest.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_63/bd_48ac_m05s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/dipen/Kintex7/BasictTest/BasictTest.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_64/bd_48ac_m05arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/dipen/Kintex7/BasictTest/BasictTest.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_65/bd_48ac_m05rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/dipen/Kintex7/BasictTest/BasictTest.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_66/bd_48ac_m05awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/dipen/Kintex7/BasictTest/BasictTest.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_67/bd_48ac_m05wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/dipen/Kintex7/BasictTest/BasictTest.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_68/bd_48ac_m05bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/dipen/Kintex7/BasictTest/BasictTest.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/ooc.xdc]
set_property used_in_implementation false [get_files -all /home/dipen/Kintex7/BasictTest/BasictTest.srcs/sources_1/bd/design_1/ip/design_1_mig_7series_0_3/design_1_mig_7series_0_3/user_design/constraints/design_1_mig_7series_0_3.xdc]
set_property used_in_implementation false [get_files -all /home/dipen/Kintex7/BasictTest/BasictTest.srcs/sources_1/bd/design_1/ip/design_1_mig_7series_0_3/design_1_mig_7series_0_3/user_design/constraints/design_1_mig_7series_0_3_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/dipen/Kintex7/BasictTest/BasictTest.srcs/sources_1/bd/design_1/ip/design_1_mig_7series_0_3/design_1_mig_7series_0_3_board.xdc]
set_property used_in_implementation false [get_files -all /home/dipen/Kintex7/BasictTest/BasictTest.srcs/sources_1/bd/design_1/ip/design_1_rst_mig_7series_0_133M_3/design_1_rst_mig_7series_0_133M_3_board.xdc]
set_property used_in_implementation false [get_files -all /home/dipen/Kintex7/BasictTest/BasictTest.srcs/sources_1/bd/design_1/ip/design_1_rst_mig_7series_0_133M_3/design_1_rst_mig_7series_0_133M_3.xdc]
set_property used_in_implementation false [get_files -all /home/dipen/Kintex7/BasictTest/BasictTest.srcs/sources_1/bd/design_1/ip/design_1_rst_mig_7series_0_133M_1_2/design_1_rst_mig_7series_0_133M_1_2_board.xdc]
set_property used_in_implementation false [get_files -all /home/dipen/Kintex7/BasictTest/BasictTest.srcs/sources_1/bd/design_1/ip/design_1_rst_mig_7series_0_133M_1_2/design_1_rst_mig_7series_0_133M_1_2.xdc]
set_property used_in_implementation false [get_files -all /home/dipen/Kintex7/BasictTest/BasictTest.srcs/sources_1/bd/design_1/design_1_ooc.xdc]

OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/dipen/Kintex7/BasictTest/BasictTest.srcs/constrs_1/new/constraints.xdc
set_property used_in_implementation false [get_files /home/dipen/Kintex7/BasictTest/BasictTest.srcs/constrs_1/new/constraints.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top design_1_wrapper -part xc7k480tffg1156-2
OPTRACE "synth_design" END { }


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef design_1_wrapper.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
create_report "synth_1_synth_report_utilization_0" "report_utilization -file design_1_wrapper_utilization_synth.rpt -pb design_1_wrapper_utilization_synth.pb"
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
