# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/constraints.xdc

# Block Designs: bd/design_1/design_1.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xdma_0_2/design_1_xdma_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xdma_0_2 || ORIG_REF_NAME==design_1_xdma_0_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xdma_0_2/ip_4/pcie2_fifo_generator_tgt_brdg.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pcie2_fifo_generator_tgt_brdg || ORIG_REF_NAME==pcie2_fifo_generator_tgt_brdg} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xdma_0_2/ip_3/pcie2_fifo_generator_dma_cpl.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pcie2_fifo_generator_dma_cpl || ORIG_REF_NAME==pcie2_fifo_generator_dma_cpl} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xdma_0_2/ip_2/xdma_v4_1_6_blk_mem_64_noreg_be.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==xdma_v4_1_6_blk_mem_64_noreg_be || ORIG_REF_NAME==xdma_v4_1_6_blk_mem_64_noreg_be} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xdma_0_2/ip_1/xdma_v4_1_6_blk_mem_64_reg_be.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==xdma_v4_1_6_blk_mem_64_reg_be || ORIG_REF_NAME==xdma_v4_1_6_blk_mem_64_reg_be} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xdma_0_2/ip_0/design_1_xdma_0_2_pcie2_ip.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xdma_0_2_pcie2_ip || ORIG_REF_NAME==design_1_xdma_0_2_pcie2_ip} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_gpio_0_1/design_1_axi_gpio_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axi_gpio_0_1 || ORIG_REF_NAME==design_1_axi_gpio_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_iic_0_0/design_1_axi_iic_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axi_iic_0_0 || ORIG_REF_NAME==design_1_axi_iic_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_util_ds_buf_1/design_1_util_ds_buf_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_util_ds_buf_1 || ORIG_REF_NAME==design_1_util_ds_buf_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_smartconnect_0_0/design_1_smartconnect_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_smartconnect_0_0 || ORIG_REF_NAME==design_1_smartconnect_0_0} -quiet] -quiet

# Block Designs: bd/design_1/ip/design_1_smartconnect_0_0/bd_0/bd_48ac.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_0/bd_48ac_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_1/bd_48ac_psr0_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_2/bd_48ac_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_3/bd_48ac_psr_aclk1_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_4/bd_48ac_psr_aclk2_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_5/bd_48ac_arsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_6/bd_48ac_rsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_7/bd_48ac_awsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_8/bd_48ac_wsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_9/bd_48ac_bsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_10/bd_48ac_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_11/bd_48ac_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_12/bd_48ac_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_13/bd_48ac_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_14/bd_48ac_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_15/bd_48ac_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_16/bd_48ac_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_17/bd_48ac_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_18/bd_48ac_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_19/bd_48ac_s01mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_20/bd_48ac_s01tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_21/bd_48ac_s01sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_22/bd_48ac_s01a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_23/bd_48ac_sarn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_24/bd_48ac_srn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_25/bd_48ac_sawn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_26/bd_48ac_swn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_27/bd_48ac_sbn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_28/bd_48ac_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_29/bd_48ac_m00arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_30/bd_48ac_m00rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_31/bd_48ac_m00awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_32/bd_48ac_m00wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_33/bd_48ac_m00bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_34/bd_48ac_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_35/bd_48ac_m01s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_36/bd_48ac_m01arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_37/bd_48ac_m01rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_38/bd_48ac_m01awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_39/bd_48ac_m01wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_40/bd_48ac_m01bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_41/bd_48ac_m01e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_1/ip/design_1_mig_7series_0_3/design_1_mig_7series_0_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_mig_7series_0_3 || ORIG_REF_NAME==design_1_mig_7series_0_3} -quiet] -quiet

# IP: bd/design_1/ip/design_1_rst_mig_7series_0_133M_3/design_1_rst_mig_7series_0_133M_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_rst_mig_7series_0_133M_3 || ORIG_REF_NAME==design_1_rst_mig_7series_0_133M_3} -quiet] -quiet

# IP: bd/design_1/ip/design_1_rst_mig_7series_0_133M_1_2/design_1_rst_mig_7series_0_133M_1_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_rst_mig_7series_0_133M_1_2 || ORIG_REF_NAME==design_1_rst_mig_7series_0_133M_1_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xbar_0/design_1_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xbar_0 || ORIG_REF_NAME==design_1_xbar_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_interconnect_0_0/design_1_axi_interconnect_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axi_interconnect_0_0 || ORIG_REF_NAME==design_1_axi_interconnect_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_dma_test_0_0/design_1_axi_dma_test_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axi_dma_test_0_0 || ORIG_REF_NAME==design_1_axi_dma_test_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_cc_0/design_1_auto_cc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_auto_cc_0 || ORIG_REF_NAME==design_1_auto_cc_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_cc_1/design_1_auto_cc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_auto_cc_1 || ORIG_REF_NAME==design_1_auto_cc_1} -quiet] -quiet

# XDC: bd/design_1/ip/design_1_xdma_0_2/ip_4/pcie2_fifo_generator_tgt_brdg.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==pcie2_fifo_generator_tgt_brdg || ORIG_REF_NAME==pcie2_fifo_generator_tgt_brdg} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/design_1/ip/design_1_xdma_0_2/ip_3/pcie2_fifo_generator_dma_cpl.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==pcie2_fifo_generator_dma_cpl || ORIG_REF_NAME==pcie2_fifo_generator_dma_cpl} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/design_1/ip/design_1_xdma_0_2/ip_2/xdma_v4_1_6_blk_mem_64_noreg_be_ooc.xdc

# XDC: bd/design_1/ip/design_1_xdma_0_2/ip_1/xdma_v4_1_6_blk_mem_64_reg_be_ooc.xdc

# XDC: bd/design_1/ip/design_1_xdma_0_2/ip_0/source/design_1_xdma_0_2_pcie2_ip-PCIE_X0Y0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_xdma_0_2_pcie2_ip || ORIG_REF_NAME==design_1_xdma_0_2_pcie2_ip} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/design_1/ip/design_1_xdma_0_2/ip_0/synth/design_1_xdma_0_2_pcie2_ip_ooc.xdc

# XDC: bd/design_1/ip/design_1_xdma_0_2/design_1_xdma_0_2_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_xdma_0_2 || ORIG_REF_NAME==design_1_xdma_0_2} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/design_1/ip/design_1_xdma_0_2/source/design_1_xdma_0_2_pcie3_7vx_ip.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_xdma_0_2 || ORIG_REF_NAME==design_1_xdma_0_2} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/design_1/ip/design_1_xdma_0_2/synth/design_1_xdma_0_2_ooc.xdc

# XDC: bd/design_1/ip/design_1_axi_gpio_0_1/design_1_axi_gpio_0_1_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_axi_gpio_0_1 || ORIG_REF_NAME==design_1_axi_gpio_0_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/design_1/ip/design_1_axi_gpio_0_1/design_1_axi_gpio_0_1_ooc.xdc

# XDC: bd/design_1/ip/design_1_axi_gpio_0_1/design_1_axi_gpio_0_1.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_axi_gpio_0_1 || ORIG_REF_NAME==design_1_axi_gpio_0_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/design_1/ip/design_1_axi_iic_0_0/design_1_axi_iic_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_axi_iic_0_0 || ORIG_REF_NAME==design_1_axi_iic_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/design_1/ip/design_1_axi_iic_0_0/design_1_axi_iic_0_0_ooc.xdc

# XDC: bd/design_1/ip/design_1_util_ds_buf_1/design_1_util_ds_buf_1_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_util_ds_buf_1 || ORIG_REF_NAME==design_1_util_ds_buf_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/design_1/ip/design_1_util_ds_buf_1/design_1_util_ds_buf_1_ooc.xdc

# XDC: bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_1/bd_48ac_psr0_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_1/bd_48ac_psr0_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_2/bd_48ac_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_2/bd_48ac_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_3/bd_48ac_psr_aclk1_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_3/bd_48ac_psr_aclk1_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_4/bd_48ac_psr_aclk2_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_4/bd_48ac_psr_aclk2_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_5/bd_48ac_arsw_0_ooc.xdc

# XDC: bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_6/bd_48ac_rsw_0_ooc.xdc

# XDC: bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_7/bd_48ac_awsw_0_ooc.xdc

# XDC: bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_8/bd_48ac_wsw_0_ooc.xdc

# XDC: bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_9/bd_48ac_bsw_0_ooc.xdc

# XDC: bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_13/bd_48ac_s00a2s_0_ooc.xdc

# XDC: bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_14/bd_48ac_sarn_0_ooc.xdc

# XDC: bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_15/bd_48ac_srn_0_ooc.xdc

# XDC: bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_16/bd_48ac_sawn_0_ooc.xdc

# XDC: bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_17/bd_48ac_swn_0_ooc.xdc

# XDC: bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_18/bd_48ac_sbn_0_ooc.xdc

# XDC: bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_22/bd_48ac_s01a2s_0_ooc.xdc

# XDC: bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_23/bd_48ac_sarn_1_ooc.xdc

# XDC: bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_24/bd_48ac_srn_1_ooc.xdc

# XDC: bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_25/bd_48ac_sawn_1_ooc.xdc

# XDC: bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_26/bd_48ac_swn_1_ooc.xdc

# XDC: bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_27/bd_48ac_sbn_1_ooc.xdc

# XDC: bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_28/bd_48ac_m00s2a_0_ooc.xdc

# XDC: bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_29/bd_48ac_m00arn_0_ooc.xdc

# XDC: bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_30/bd_48ac_m00rn_0_ooc.xdc

# XDC: bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_31/bd_48ac_m00awn_0_ooc.xdc

# XDC: bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_32/bd_48ac_m00wn_0_ooc.xdc

# XDC: bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_33/bd_48ac_m00bn_0_ooc.xdc

# XDC: bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_35/bd_48ac_m01s2a_0_ooc.xdc

# XDC: bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_36/bd_48ac_m01arn_0_ooc.xdc

# XDC: bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_37/bd_48ac_m01rn_0_ooc.xdc

# XDC: bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_38/bd_48ac_m01awn_0_ooc.xdc

# XDC: bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_39/bd_48ac_m01wn_0_ooc.xdc

# XDC: bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_40/bd_48ac_m01bn_0_ooc.xdc

# XDC: bd/design_1/ip/design_1_smartconnect_0_0/ooc.xdc

# XDC: bd/design_1/ip/design_1_mig_7series_0_3/design_1_mig_7series_0_3/user_design/constraints/design_1_mig_7series_0_3.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_mig_7series_0_3 || ORIG_REF_NAME==design_1_mig_7series_0_3} -quiet] -quiet

# XDC: bd/design_1/ip/design_1_mig_7series_0_3/design_1_mig_7series_0_3/user_design/constraints/design_1_mig_7series_0_3_ooc.xdc

# XDC: bd/design_1/ip/design_1_mig_7series_0_3/design_1_mig_7series_0_3_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_mig_7series_0_3 || ORIG_REF_NAME==design_1_mig_7series_0_3} -quiet] -quiet

# XDC: bd/design_1/ip/design_1_rst_mig_7series_0_133M_3/design_1_rst_mig_7series_0_133M_3_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_rst_mig_7series_0_133M_3 || ORIG_REF_NAME==design_1_rst_mig_7series_0_133M_3} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/design_1/ip/design_1_rst_mig_7series_0_133M_3/design_1_rst_mig_7series_0_133M_3.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_rst_mig_7series_0_133M_3 || ORIG_REF_NAME==design_1_rst_mig_7series_0_133M_3} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/design_1/ip/design_1_rst_mig_7series_0_133M_1_2/design_1_rst_mig_7series_0_133M_1_2_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_rst_mig_7series_0_133M_1_2 || ORIG_REF_NAME==design_1_rst_mig_7series_0_133M_1_2} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/design_1/ip/design_1_rst_mig_7series_0_133M_1_2/design_1_rst_mig_7series_0_133M_1_2.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_rst_mig_7series_0_133M_1_2 || ORIG_REF_NAME==design_1_rst_mig_7series_0_133M_1_2} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/design_1/ip/design_1_xbar_0/design_1_xbar_0_ooc.xdc

# XDC: bd/design_1/ip/design_1_auto_cc_0/design_1_auto_cc_0_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_auto_cc_0 || ORIG_REF_NAME==design_1_auto_cc_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/design_1/ip/design_1_auto_cc_0/design_1_auto_cc_0_ooc.xdc

# XDC: bd/design_1/ip/design_1_auto_cc_1/design_1_auto_cc_1_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_auto_cc_1 || ORIG_REF_NAME==design_1_auto_cc_1} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/design_1/ip/design_1_auto_cc_1/design_1_auto_cc_1_ooc.xdc

# XDC: bd/design_1/design_1_ooc.xdc
