###################################################################################################
## This constraints file contains default clock frequencies to be used during creation of a 
## Synthesis Design Checkpoint (DCP). For best results the frequencies should be modified 
## to match the target frequencies. 
## This constraints file is not used in top-down/global synthesis (not the default flow of Vivado).
###################################################################################################


##################################################################################################
## 
##  Xilinx, Inc. 2010            www.xilinx.com 
##  Tue Sep 22 21:55:14 2026

##  Generated by MIG Version 4.2
##  
##################################################################################################
##  File name :       design_1_mig_7series_0_3.xdc
##  Details :     Constraints file
##                    FPGA Family:       KINTEX7
##                    FPGA Part:         XC7K480T-FFG1156
##                    Speedgrade:        -2
##                    Design Entry:      VERILOG
##                    Frequency:         533.33000000000004 MHz
##                    Time Period:       1875 ps
##################################################################################################

##################################################################################################
## Controller 0
## Memory Device: DDR3_SDRAM->Components->MT41K256M8XX-125
## Data Width: 72
## Time Period: 1875
## Data Mask: 0
#####################################################################################################################################################################################################
## This constraints file contains default clock frequencies to be used during creation of a 
## Synthesis Design Checkpoint (DCP). For best results the frequencies should be modified 
## to match the target frequencies. 
## This constraints file is not used in top-down/global synthesis (not the default flow of Vivado).
###################################################################################################



##################################################################################################
## Controller 1
## Memory Device: DDR3_SDRAM->Components->MT41K256M8XX-125
## Data Width: 72
## Time Period: 1875
## Data Mask: 0
##################################################################################################